Check buildkite-agent and docker too

diff --git a/packer/conf/buildkite-agent/scripts/check-instance-health b/packer/conf/buildkite-agent/scripts/check-instance-health
--- a/packer/conf/buildkite-agent/scripts/check-instance-health
+++ b/packer/conf/buildkite-agent/scripts/check-instance-health
@@ -15,7 +15,7 @@ check_disk_healthy() {
   echo "Disk space free: $disk_avail"
 
   if [[ $disk_avail -lt $DISK_MIN_AVAILABLE ]]; then
-    echo "Not enough disk space free"
+    echo "Not enough disk space free" >&2
     return 1
   fi
 
@@ -23,9 +23,17 @@ check_disk_healthy() {
   echo "Inodes free: $inodes_avail"
 
   if [[ $inodes_avail -lt $DISK_MIN_INODES ]]; then
-    echo "Not enough inodes free"
+    echo "Not enough inodes free" >&2
     return 1
   fi
+}
+
+check_buildkite_agent_healthy() {
+  pgrep -f buildkite-agent
+}
+
+check_docker_healthy() {
+  timeout 30 docker ps -q
 }
 
 trap mark_instance_unhealthy ERR
@@ -35,7 +43,17 @@ if ! check_disk_healthy ; then
   docker system prune -a -f
 
   if ! check_disk_healthy ; then
-    echo "Disk health checks failed"
+    echo "Disk health checks failed" >&2
     exit 1
   fi
+fi
+
+if ! check_docker_healthy ; then
+  echo "Docker health checks failed" >&2
+  exit 2
+fi
+
+if ! check_buildkite_agent_healthy ; then
+  echo "Buildkite-agent health checks failed" >&2
+  exit 2
 fi
