Check sshkeys and env download properly, closes #172

diff --git a/packer/conf/buildkite-agent/hooks/environment b/packer/conf/buildkite-agent/hooks/environment
--- a/packer/conf/buildkite-agent/hooks/environment
+++ b/packer/conf/buildkite-agent/hooks/environment
@@ -66,7 +66,11 @@ if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" ]] ; then
   for key in ${ssh_key_paths[*]} ; do
     if s3_exists "${BUILDKITE_SECRETS_BUCKET}" "$key" ; then
       echo "Downloading ssh-key $key"
-      SSH_ASKPASS="/bin/false" ssh-add <(s3_download "${BUILDKITE_SECRETS_BUCKET}" "$key")
+      if ! ssh_key=$(s3_download "${BUILDKITE_SECRETS_BUCKET}" "$key") ; then
+        echo "~~~ :warning: Failed to download ssh-key $key"
+        exit 1
+      fi
+      SSH_ASKPASS="/bin/false" ssh-add <(cat $ssh_key)
       key_found=1
       break
     fi
@@ -86,8 +90,12 @@ if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" ]] ; then
 
   for key in ${env_paths[*]} ; do
     if s3_exists "${BUILDKITE_SECRETS_BUCKET}" "$key" ; then
+      if ! envvars=$(s3_download "${BUILDKITE_SECRETS_BUCKET}" "$key") ; then
+        echo "~~~ :warning: Failed to download env from $key"
+        exit 1
+      fi
       echo "Downloading env $key"
-      eval "$(s3_download "${BUILDKITE_SECRETS_BUCKET}" "$key")"
+      eval "$envvars"
     fi
   done
 fi
