Fail if ecr login fails

diff --git a/packer/conf/buildkite-agent/hooks/pre-command b/packer/conf/buildkite-agent/hooks/pre-command
--- a/packer/conf/buildkite-agent/hooks/pre-command
+++ b/packer/conf/buildkite-agent/hooks/pre-command
@@ -7,13 +7,21 @@ set -eu -o pipefail
 # For logging into the current AWS account’s registry
 if [[ "${AWS_ECR_LOGIN:-}" =~ ^(true|1)$ ]] ; then
   echo "~~~ Authenticating with AWS ECR"
-  eval "$(aws ecr get-login)"
+  if ! ecr_login=$(aws ecr get-login) ; then
+    echo echo "~~~ :warning: ECR login failed"
+    exit 1
+  fi
+  eval "$ecr_login"
 fi
 
 # For logging into other AWS account’s registries
 if [[ -n "${AWS_ECR_LOGIN_REGISTRY_IDS:-}" ]] ; then
   echo "~~~ Authenticating with AWS ECR"
-  eval "$(aws ecr get-login --registry-ids "${AWS_ECR_LOGIN_REGISTRY_IDS}")"
+  if ! ecr_login=$(aws ecr get-login --registry-ids "${AWS_ECR_LOGIN_REGISTRY_IDS}") ; then
+    echo echo "~~~ :warning: ECR login failed"
+    exit 1
+  fi
+  eval "$ecr_login"
 fi
 
 # DOCKER_HUB_* legacy config var support
