Cleanup environment hook messages

diff --git a/packer/conf/hooks/environment b/packer/conf/hooks/environment
--- a/packer/conf/hooks/environment
+++ b/packer/conf/hooks/environment
@@ -1,6 +1,15 @@
 #!/bin/bash
 set -eu
 
+download_github_key() {
+  local key_url="s3://${BUILDKITE_SECRETS_BUCKET}/$1"
+  echo "~~~ Downloading encrypted github ssh key from $key_url" >&2
+  if ! env -i aws s3 cp --sse-c --sse-c-key "$BUILDKITE_SECRETS_KEY" "$key_url" - l ; then
+    echo "Failed to download and decrypt $key_url"  >&2
+    return 1
+  fi
+}
+
 echo '+++ :house_with_garden: Setting up the environment'
 
 source ~/cfn-env
@@ -11,19 +20,10 @@ if [[ -n "$BUILDKITE_SECRETS_BUCKET" ]] && [[ -z "$BUILDKITE_SECRETS_KEY" ]] ; t
 fi
 
 SSH_KEY_NAME="${SSH_KEY_NAME:-id_rsa_github}"
-SSH_KEY_URL="s3://${BUILDKITE_SECRETS_BUCKET}/$SSH_KEY_NAME"
-
-if ! github_ssh_key=$(env -i aws s3 cp --sse-c --sse-c-key "$BUILDKITE_SECRETS_KEY" "$SSH_KEY_URL") ; then
-  echo "Failed to download and decrypt $SSH_KEY_URL"
-fi
-
-eval "$(ssh-agent -s)"
 
 # startup an ssh-agent with the ssh-key
-if [[ -n "${SSH_KEY_URL:-}" ]] ; then
-  echo "~~~ Downloading github ssh key from $SSH_KEY_URL"
-  ssh-add <(echo $github_ssh_key)
-fi
+eval "$(ssh-agent -s)"
+ssh-add <(download_github_key "$SSH_KEY_NAME")
 
 if [[ $(docker ps -q | wc -l) -gt 0 ]] ; then
   echo "~~~ Stopping existing :docker: containers"
